### ISSUE TITLE
[Bug]: can't use 1.19.4 file on 1.19.2 server

### ISSUE THREAD

**Issue by MoonMoonShark** [TheIllusiveC4/CreaturesLoveBeacons#7]
### Minecraft Version

1.19.2

### What happened?

there's a version of the mod that is listed for 1.19.2, but the file name is 1.19.4, and when i try to run it on my server, the server rejects it because it's looking for 1.19.4 and my server is 1.19.2. so i guess either it needs to not be listed as 1.19.2 compatible on curseforge, or change the requirements within the mod itself. either way works for me, just figured i'd let you know. :)

i appreciate all your help on this! please let me know if there's anything

### How do you trigger this bug?

1. upload beaconsforall-forge-6.1.0-1.19.4.jar to server
2. start server
3. server stops loading with error
...

### Loader

Forge

### Loader Version

Forge 43.2.23

### Mod Version

beaconsforall-forge-6.1.0-1.19.4.jar

### Relevant Log Outputs

https://pastebin.com/WbJKx974

**Comment by TheIllusiveC4** [comment]
Thanks for catching this, this was a mistake I made in the mod files listing a version it doesn't actually need. I can't exactly go back and edit that though so I've just delisted the other versions from the metadata and now it should only be listed for 1.19.4 and the previous 1.19.2 files will be the ones suggested for 1.19.2.

**Comment by MoonMoonShark** [comment]
works for me. thank you for everything! <3
